name: site
on:
  push:
    tags:
      - site*

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
        pnpm install --no-frozen-lockfile
        pnpm build:site
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
